import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import GlobalState from "../context";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Attire Alley: Find your fit",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        <GlobalState>
          <Navbar />
          <ToastContainer />
          <main className=" flex h-full w-full items-center justify-center bg-background p-6 dark:bg-backgroundDark">
            {children}
          </main>
        </GlobalState>
      </body>
    </html>
  );
}
