import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import GlobalState from "../context";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Attire Alley: Find your fit",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <GlobalState>
          <Navbar />
          <ToastContainer />
          <main className="flex flex-grow flex-col">
            {children}
          </main>
          <Footer />
        </GlobalState>
      </body>
    </html>
  );
}
