import "./globals.css";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import GlobalState from "../context";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { Instrument_Serif, JetBrains_Mono } from "next/font/google";

const instrumentSerif = Instrument_Serif({
  weight: "400",
  style: ["normal", "italic"],
  variable: "--font-display",
  subsets: ["latin"],
  display: "swap",
});

const jetbrainsMono = JetBrains_Mono({
  weight: ["400", "500"],
  variable: "--font-mono",
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Attire Alley: Find your fit",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${instrumentSerif.variable} ${jetbrainsMono.variable}`}>
      <body>
        <GlobalState>
          <Navbar />
          <ToastContainer />
          <main className="flex flex-grow flex-col">
            {children}
          </main>
          <Footer />
        </GlobalState>
      </body>
    </html>
  );
}
